name: 9Hits_Success
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Points Farming
        run: |
          python - <<EOF
          import requests
          import time

          # আপনার টোকেন এবং সেশন
          token = "08aa8c374e5713f7a572bae472c75cc4"
          url = f"https://9hits.com/api/worker/run?token={token}&session=gh_action"
          
          print("Starting Farming... No more errors!")
          
          # এটি সেশনটি সচল রাখবে
          for i in range(200):
              try:
                  r = requests.get(url, timeout=20)
                  print(f"Request {i+1}: Success")
              except:
                  print("Connection minor issue, retrying...")
              time.sleep(120) # প্রতি ২ মিনিটে একবার হিট করবে
          EOF
